### ISSUE TITLE
Add to danger.systems

### ISSUE THREAD

**Issue by k0nserv** [wojteklu/danger-mention#2]
Hi @wojteklu,

maybe you should look at getting this added to the danger website at http://danger.systems. Not sure exactly what the process is, but I believe you send a PR to https://github.com/danger/danger.systems

**Comment by wojteklu** [comment]
Thanks for the suggestion. I found that process is described here: http://danger.systems/guides/creating_your_first_plugin.html. I will fix issues and send a pull request to danger.systems/plugins.json.

**Comment by wojteklu** [comment]
Done. Thanks for the suggestion!
